name: Ejecutar RemBot

on:
  schedule:
    # Ejecutar lunes, miércoles y domingos a las 6:00 p.m. UTC (ajusta si estás en otro huso horario)
    - cron: '0 18 * * 0,1,3'
    # Ejecutar viernes a las 8:00 a.m. UTC
    - cron: '0 8 * * 5'
  workflow_dispatch:  # permite ejecución manual desde GitHub

jobs:
  run-rembot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar RemBot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python RemBot.py
