name: Ejecutar RemBot

on:
  workflow_dispatch:  # Esto permite ejecutarlo manualmente desde GitHub

jobs:
  run-rembot:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install python-dotenv requests

      - name: Ejecutar RemBot.py
        run: python RemBot.py